### PR TITLE
Make warning persistent if user has a Google Maps key and is using TSML UI

### PR DESCRIPTION
**Pull request by gobborg**
image

### CODE REVIEW

**Comment by joshreisner** [comment]
thanks for picking this up! i think it'd be great to simplify this actually and just make this a paragraph that's always there in the maps box. i kind of think these alerts are a nuisance, and feel spammy to me. wdyt?

Screenshot 2024-06-21 at 3 50 05 PM

**Comment by joshreisner** [comment]
sorry for not flagging that sooner! seeing the other alerts in the screeshot kind of clarified it for me a little

**Comment by gobborg** [comment]
I'm fine with moving it to the map API keys box, but do you still want the display to be conditional on
`if (empty($tsml_mapbox_key) && ($tsml_user_interface == 'tsml_ui'))`
or always part of the paragraph?

**Comment by joshreisner** [comment]
i say let's keep it simple and always show it

**Comment by gobborg** [comment]
Before I make changes, let's proof the paragraph:

"Display of maps requires an authorization key from [Mapbox](https://www.mapbox.com/) or [Google](https://console.cloud.google.com/home/). Please note that TSML UI only supports Mapbox."

**Comment by joshreisner** [comment]
i think it's clearer as two paragraphs, per the screenshot

**Comment by gobborg** [comment]
I should get my eyes checked. Thanks for your patience.

**Review by joshreisner — APPROVED** [review]
thanks! it would be cool to fix the indentation if possible. but not a blocker. otherwise it'll get fixed by the next commit on this page

**Pull request merged**
