### PR TITLE
Add upcoming widget text for no meetings

### PR DESCRIPTION
**Pull request by pjaudiomv**
Screen Shot 2020-01-15 at 2 22 18 PM
Screen Shot 2020-01-15 at 2 22 44 PM

### CODE REVIEW

**Comment by pjaudiomv** [comment]
I tried to keep this as simple as possible. If message is set and meeting count for upcoming meetings is 0 this will,  display the widget with a message and view more button will link to all meetings instead of upcoming.

**Comment by tech2serve** [comment]
I like the simplicity!

My concern right now is that in testing this, I may have found an issue with the plugin writ large. To test the plugin, I deleted the meetings for today. Confirmed that the PR displayed the message I entered instead of having the widget disappear.

Then, to continue testing, I restored two meetings from the trash. None of them showed up in the widget OR the meeting list. I then edited one of the meetings, and it then shows up on the meeting page, but not the widget.

image

image

image

Any idea why this might be happening?

**Comment by pjaudiomv** [comment]
hmm interesting, I will test the way you have and check it out.

**Comment by tech2serve** [comment]
Thank you. I'm definitely not ruling out that it could be something with my system. I get weirdness with the meeting page sometimes not being found. Not clear errors, so I'm assuming it could be a vhost/Apache config problem.

**Comment by pjaudiomv** [comment]
yea if your getting it other people could. I've been doing most my testing using this docker image `wordpress:5.3.2-php7.2-apache` but like to test on shared hosting as I can miss problems that arise on shared hosting providers. I should be able to get to further testing later today.

**Comment by pjaudiomv** [comment]
ok found a small issue with meetings link fixed that.

**Comment by pjaudiomv** [comment]
I was able to replicate your issue, this is an existing issue that has nothing to do with PR or my changes. What was interesting is I was not able to reproduce in my container, everything worked fine. However I tested in a sandbox i have on Bluehost and Siteground and both had this issue, once i restored meeting I ahd to make a small change and save for it to appear again.

**Comment by pjaudiomv** [comment]
created ticket here to track https://github.com/code4recovery/12-step-meeting-list/issues/56

**Comment by joshreisner** [comment]
I do have some minor feedback on the branch, but didn't have permission to make a change. I added my suggestions to this branch:

https://github.com/code4recovery/12-step-meeting-list/commit/c2e6222af328c0cdef5feb51704e7f7128eb60dc

* add a basic style to the message if the "Style with CSS?" checkbox is checked
* renamed the CSS class to prevent conflicts
* tweaked widget field label

**Comment by pjaudiomv** [comment]
Thanks makes sense. Yea I forked, didn't think I had perms to push a branch. I'll
Merge your changes into my fork then rebase and push.

**Comment by tech2serve** [comment]
Since most of this change (and the previous) have been new features/feature adds, any objection to making this release 3.5 vice 3.4.23?

**Comment by pjaudiomv** [comment]
My only objection would be that it should be 3.5.0, but not sure how strictly you follow semver guidelines

**Comment by tech2serve** [comment]
You're correct. I was being sloppy with my writing :-) 3.5.0.

**Comment by joshreisner** [comment]
Sounds good!

**Pull request merged**
