### PR TITLE
Automating JSON Feeds #42

### PR DESCRIPTION
**Pull request by wokat**
# JSON Feeds via Cron Job

See issue #42 

This branch implements regular, unsupervised imports of existing json data sources.

This changes the import behaviour from "delete all, reimport" to "mark as stale, update, delete untouched meetings".

Import batches now run until about 80% of script's max_execution_time is reached. **This can easily be changed to trying to extend execution time instead.** But author elected to not bother in this branch, as cheap hosting probably usually would thwart attempts at that. Lock breaking (see below) also depends on that for a cheap, transparent solution.

While an import batch is being processed, the import is locked. Automatic lock breaking occurs after script_max_execution_time, assuming that the predecessor of an import process either finished by then or failed.

Branch also adds a **"Parent Region"** that can be specified with each data source. Contained meetings' regions will be appended to that region, if not yet existing as a child of it or its ancestors.

This adds **two cron jobs**:

* tsml_cron_invalidate_data_sources 
  * Configurable schedule
  * Marks meetings as stale and sets the "import buffer" option
* tsml_cron_import_data_source_batch
  * Runs every 10 minutes, if cron spawning is being used
  * Runs every 1 minute, if cron spawning is switched off
  * Imports meeting after meeting
  * Until about 80% of max_execution_time is reached
  * Then rewrites import buffer option
  * And refreshes cache

## Settings

Import & Settings page now contains dropdowns for selecting the parent region of a new data source, and for setting the schedule of the invalidation of **all data sources at once**.

Schedule setting ignores actual schedule state and just reschedules on change.

Cron jobs are disabled by default, and can be disabled via the schedule setting.

## Testing

Tested in last few WordPress releases as they went by, but no dedicated testing.

You can use "WP Crontrol" for cron job inspection and scheduling for testing.

### CODE REVIEW

**Comment by mleahy-rns** [comment]
Is there any update on this? I'm using the latest version 3.9.3 of the plugin and I don't see any other options for automating data source imports.

**Comment by tech2serve** [comment]
> Is there any update on this? I'm using the latest version 3.9.3 of the plugin and I don't see any other options for automating data source imports.

Unfortunately, no. We've not had the bandwidth nor the expertise to test this PR. When I tried, it was not successful. I reached out to the originator of the PR, but he seems to have disappeared. 

cc: @wokat

**Comment by kiyote33** [comment]
Hi folks,
I'm a retired developer. I might be able to assist in getting this tested and ready for release.  

Let me know...

**Comment by 97eighty** [comment]
@kiyote33 

I have this on my list but was waiting until an upcoming milestone was released. Tackle it if you want. I haven't started merging to two.

**Pull request closed without merging**
