### PR TITLE
These changes address Issue #146 - Sorting by location is not working…

### PR DESCRIPTION
**Pull request by crispyatl**
… as expected.

In short, sorting works fine for English, but not for many other languages.

Modification Summary

- includes/functions.php:
  - Added tsml_sanitize_data_sort() function.  It is similar to sanitize_title() but it works with UNICODE
- templates/archive-meetings.php:
  - Modified meeting element data-sort attribute to use tsml_sanitize_data_sort() instead of sanitize_title()
- assets/src/public.js:
  - Added sanitizeDataSort() function.  It is similar to sanitizeTitle() but it works with UNICODE
  - Modified meeting element data-sort attribute to use sanitizeDataSort() instead of sanitizeTitle()
  - Modified sortMeetings() to use Intl.Collate() so that sorts are done in a locale-aware fashion.  Previous sort was locale-naïve

### CODE REVIEW

**Comment by joshreisner** [comment]
Hey @crispyatl thanks for working on this! @tech2serve would be a better resource here. Thanks

**Comment by crispyatl** [comment]
> Hey @crispyatl thanks for working on this! @tech2serve would be a better resource here. Thanks

Yep - We're already working together on it. Thanks!

**Comment by tech2serve** [comment]
I'm trying to address the conflict with the minified files. I've applied the minified files from `develop` using a suggestion from StackOverflow, but when I tried to push it back, I couldn't use the same ref, and Git ended up creating a new branch. So, now I'm researching.

**Comment by joshreisner** [comment]
this is weird, hope no one minds but I'm going to try to resolve the conflict

**Comment by tech2serve** [comment]
I think I have the steps figured out, and don’t mind doing it.

**Comment by joshreisner** [comment]
@tech2serve sorry didn't see your comment, hope I didn't mess anything up. basically I just pulled down this branch, updated it, and then re-ran `npm run prod` and I think that should take care of it, hopefully

**Comment by tech2serve** [comment]
No problem! Thanks for the assist.

**Pull request merged**
