### PR TITLE
Widget on the main WordPress Dashboard

### PR DESCRIPTION
**Pull request by brianw-area24**
This pull request adds a widget on the main WordPress Dashboard to highlight things about Code for Recovery is doing. It addresses the initial post of Issue #595, but not the comments which suggest some farther enhancements.

Some initial questions on this include, includes/admin_menu.php an acceptable place to put this code, or should it be somewhere else? Is the wording ok for this static message? And should we wait until we can pull from the website before merging this PR?

### CODE REVIEW

**Comment by joshreisner** [comment]
Thanks Brian, it definitely works, but I do see it at the bottom of the main dashboard:

main

If it were up to me, I would instead update the message at the top of the Import & Settings page:

import-and-settings

The text is good but it's a little rooted in this moment in time. I might update it to be something like:

> [logo, link] Code for Recovery [/logo, link] is a nonprofit organization of volunteer members building technology services for recovery programs, such as AA and Al-Anon. If you need help, please join our discussion forum. If you would like to makea  tax-deductible contribution, please visit our website.

> [button, discussion forum] [button, make a contribution]

**Review by joshreisner — APPROVED** [review]

**Review by 97eighty — COMMENTED** [review]
Suggest we leverage the $priority parameter to place the widget higher on the dashboard.
Contribuitions is spelled incorrectly.

**Comment by tech2serve** [comment]
> Thanks Brian, it definitely works, but I do see it at the bottom of the main dashboard:
> 
> If it were up to me, I would instead update the existing message at the top of the Import & Settings page:
> 
I've seen other plugins populate a banner on the Dashboard, which is the default page that loads when an admin logs in. I believe it would be more visible there.

> The text is good but it's a little rooted in this moment in time. I might update it to be something like:
> 
> > [logo, link] Code for Recovery [/logo, link] is a nonprofit organization of volunteer members building technology services for recovery programs, such as AA and Al-Anon. If you need help, please join our discussion forum. If you would like to makea  tax-deductible contribution, please visit our website.
> 
> > [button, discussion forum] [button, make a contribution]

I agree with Josh's suggested wording changes.

**Review by tech2serve — CHANGES_REQUESTED** [review]
1. I agree with the wording changes suggested by Josh.
2. I agree with the prioritization suggested by Mark.

**Comment by petermixt** [comment]
[logo, link] Code for Recovery [/logo, link] is a nonprofit organization of volunteer members building technology services for recovery FELLOWSHIPS, such as AA and Al-Anon. If you need help, please join our discussion forum. If you would like to make a tax-deductible contribution, please visit our website.

**Review by kiyote33 — APPROVED** [review]
Uhg... @brianw-area24  I think I screwed up again. I pushed a commit for the Switch UI Option on this pr, when I think I should have branched and pushed it to a separate pr. I'm stuck as I don't know how to reverse it. Can you fix???

**Review by kiyote33 — CHANGES_REQUESTED** [review]
This change needs to be backed out.

**Comment by tech2serve** [comment]
> Uhg... @brianw-area24 I think I screwed up again. I pushed a commit for the Switch UI Option on this pr, when I think I should have branched and pushed it to a separate pr. I'm stuck as I don't know how to reverse it. Can you fix???

I believe I've reverted both of these commits.

**Review by kiyote33 — APPROVED** [review]

**Review by tech2serve — APPROVED** [review]

**Comment by tech2serve** [comment]
Two final suggestions regarding the wording/links. 

First, I don't believe the title of the help widget needs to be quite as long. Would this work?

image

And the second would be to add a direct link to the TSML Discussions.

**Comment by kiyote33** [comment]
FYI: here's a first look at the landing tab for our refactored TSML Settings page:
image

**Comment by brianw-area24** [comment]
Thanks for the reviews, @tech2serve, I just made the two adjustment you suggested, ready for your re-review

**Comment by brianw-area24** [comment]
@tech2serve Thanks for reverting those 2 commits over the weekend.

@kiyote33 Do you have those 2 commits in a separate branch, that you could push up to GitHub, or do you want me to try to use these reverted commits to create a branch for that change?

**Review by tech2serve — APPROVED** [review]
Looks good to me!  

Thanks!

**Review by joshreisner — APPROVED** [review]

**Pull request merged**
