### PR TITLE
Fixes #593

### LINKED ISSUE #593: [Bug]:
### Contact Details

masterlifterpro@gmail.com

### Website With Issue

https://secularrecoverygroup.org

### What happened?

**12 step Plugin update failed** 

  | 12 Step Meeting ListDeactivate \| Resume | Manage a list of recovery meetings 						Version **3.12.1** \| By Code for Recovery \| View details This plugin failed to load properly and is paused during recovery mode.An error of type E_ERROR was caused in line 9 of the file /home/courtney/public_html/wp-content/plugins/12-step-meeting-list/includes/database_updates.php. Error message: Uncaught  TypeError: array_key_exists(): Argument #2 ($array) must be of type  array, bool given in  /home/courtney/public_html/wp-content/plugins/12-step-meeting-list/includes/database_updates.php:9 Stack trace: #0  /home/courtney/public_html/wp-content/plugins/12-step-meeting-list/includes/admin_meeting.php(32):  tsml_db_update_remove_all_approximate_location_cache() #1 /home/courtney/public_html/wp-includes/class-wp-hook.php(303):  {closure}('') #2 /home/courtney/public_html/wp-includes/class-wp-hook.php(327):  WP_Hook->apply_filters(NULL, Array) #3 /home/courtney/public_html/wp-includes/plugin.php(470):  WP_Hook->do_action(Array) #4 /home/courtney/public_html/wp-admin/admin.php(175):  do_action('admin_init') #5 /home/courtney/public_html/wp-admin/index.php(10):  require_once('/home/courtney/...') #6 {main}   thrown
-- | -- | --

### TSML Version

Latest (default)

### Wordpress Version

Latest (default)

### What browsers are you seeing the problem on?

Firefox

### Relevant log output/errors

```shell
An error of type E_ERROR was caused in line 9 of the file /home/courtney/public_html/wp-content/plugins/12-step-meeting-list/includes/database_updates.php. Error message: Uncaught  TypeError: array_key_exists(): Argument #2 ($array) must be of type  array, bool given in  /home/courtney/public_html/wp-content/plugins/12-step-meeting-list/includes/database_updates.php:9 Stack trace: #0  /home/courtney/public_html/wp-content/plugins/12-step-meeting-list/includes/admin_meeting.php(32):  tsml_db_update_remove_all_approximate_location_cache() #1 /home/courtney/public_html/wp-includes/class-wp-hook.php(303):  {closure}('') #2 /home/courtney/public_html/wp-includes/class-wp-hook.php(327):  WP_Hook->apply_filters(NULL, Array) #3 /home/courtney/public_html/wp-includes/plugin.php(470):  WP_Hook->do_action(Array) #4 /home/courtney/public_html/wp-admin/admin.php(175):  do_action('admin_init') #5 /home/courtney/public_html/wp-admin/index.php(10):  require_once('/home/courtney/...') #6 {main}   thrown
-- | -- | --
```

### PR DESCRIPTION
**Pull request by 97eighty**

### CODE REVIEW

**Comment by brianw-area24** [comment]
Thanks for the quick response to this issue!

Does anyone have any experience with PHP 8 compatibility checkers? It would be good if we could run the plugin through some check to catch if there are other incompatibilities.

**Comment by joshreisner** [comment]
confirmed this fixes a similar error we were having on demo.code4recovery.org

**Comment by joshreisner** [comment]
is [PHP intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client) installed? there are a lot of whitespace changes here, makes it hard to know what's changed.

**Comment by 97eighty** [comment]
> is [PHP intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client) installed? there are a lot of whitespace changes here, makes it hard to know what's changed.

Yes. Installed. I must have an incorrect setting in intelephense.

**Review by joshreisner — APPROVED** [review]
it would be great to figure it out at some point. in the meantime i pulled the changes down, hit save, and committed so the diff would be more readable

**Comment by kiyote33** [comment]
FYI on the PHP 8 compatability checker question: I've been using the validator tool at https://phpcodechecker.com. Does the job...

**Pull request merged**
